name 'myapache'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures myapache'
long_description 'Installs/Configures myapache'
version '0.1.0'
